// SSR entry — wraps the SAME provider stack `boot()` mounts on the client
// (TreeSourceProvider + AuthProvider + Router) so client hydration sees the
// exact React tree it would have rendered itself, no DOM mismatch.
//
// .ts (not .tsx) so cross-package importers don't need .ts→.tsx fallback
// in the exports map.

import { AuthProvider } from '#app/auth-context';
import { Router } from '#app/Router';
import { Toaster } from '#components/ui/sonner';
import '#mods/servers';
import { ServerLocationContext } from '#navigate';
import type { TreeSource } from '#tree/tree-source';
import { TreeSourceProvider } from '#tree/tree-source-context';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { NodeData } from '@treenx/core';
import { createElement, Fragment } from 'react';
import { renderToStaticMarkup, renderToString } from 'react-dom/server';
// Side-effect: scan engine/mods for view-site.ts and register them in the
// component registry. Vite's treenix plugin generates this barrel.
// @ts-ignore virtual module — generated by vite-plugin-treenix at build time
import 'virtual:mod-site-views';

export type RenderMode = 'static' | 'hydrate';

export type RenderArgs = {
  source: TreeSource;
  /** The route node — passed for parity with previous API; Router resolves it
   *  again from `pathname` so the rendered tree matches the client's. */
  node: NodeData;
  /** URL tail after the matched route prefix. Unused — Router computes it. */
  rest: string;
  mode: RenderMode;
  /** Full URL pathname (e.g. "/v/demo/landing"). Required — Router reads it
   *  through ServerLocationContext to mirror what client useLocation() returns. */
  pathname?: string;
  /** URL search string with leading '?' (e.g. "?ctx=site"). Read by views via
   *  useLocation().search — view-shell uses it to pick render context. */
  search?: string;
};

export function render({ source, mode, pathname = '/', search = '' }: RenderArgs): string {
  const loc = { pathname, search, href: pathname + search };
  // Mirror the exact provider stack from main.tsx boot() so hydration matches
  // element-for-element. ServerLocationContext is the only addition — it's a
  // pure React Context, no DOM, invisible to hydration's DOM diff.
  const queryClient = new QueryClient();
  const tree = createElement(
    ServerLocationContext.Provider,
    {
      value: loc,
      children: createElement(
        TreeSourceProvider,
        {
          source,
          children: createElement(
            AuthProvider,
            {
              children: createElement(
                QueryClientProvider,
                {
                  client: queryClient,
                  children: createElement(Fragment, null,
                    createElement(Router),
                    createElement(Toaster),
                  ),
                },
              ),
            },
          ),
        },
      ),
    },
  );
  return mode === 'hydrate' ? renderToString(tree) : renderToStaticMarkup(tree);
}
