// Auto-generated — do not edit
export const TEMPLATES: Record<string, string> = {
  "_base/dot-env.tmpl": "PORT=3211\nDATA_DIR=./data\n",
  "_base/dot-gitignore.tmpl": "node_modules/\ndist/\ndata/\n.env\n*.log\n",
  "_base/package.json.tmpl": "{\n  \"name\": \"{{PROJECT_NAME}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"tsx --watch src/server.ts\",\n    \"dev:front\": \"vite\",\n    \"start\": \"tsx src/server.ts\",\n    \"build\": \"tsc\",\n    \"schema\": \"tsx node_modules/@treenity/core/src/schema/extract-schemas.ts\"\n  },\n  \"dependencies\": {\n    \"@treenity/core\": \"^0.1.0\",\n    \"dotenv\": \"^17.0.0\"\n  },\n  \"devDependencies\": {\n    \"tsx\": \"^4.21.0\",\n    \"typescript\": \"^5.9.0\"\n  }\n}\n",
  "_base/src/seed.ts.tmpl": "import type { Tree } from '@treenity/core/store'\n\nexport async function seed(store: Tree) {\n  // Seed initial data here\n  // Example:\n  // if (await store.get('/demo')) return\n  // await store.set({ $path: '/demo', $type: 'dir' })\n}\n",
  "_base/src/server.ts.tmpl": "import 'dotenv/config'\nimport { treenity } from '@treenity/core/server'\nimport { seed } from './seed.js'\n\nconst app = await treenity({\n  dataDir: process.env.DATA_DIR || './data',\n  modsDir: new URL('./mods', import.meta.url).pathname,\n  seed,\n})\n\nawait app.listen(Number(process.env.PORT) || 3211, {\n  allowedOrigins: ['http://localhost:3210'],\n})\n",
  "_base/tsconfig.json.tmpl": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \"moduleResolution\": \"bundler\",\n    \"strict\": true,\n    \"outDir\": \"dist\",\n    \"rootDir\": \"src\",\n    \"noEmit\": true,\n    \"esModuleInterop\": true,\n    \"skipLibCheck\": true,\n    \"resolveJsonModule\": true,\n    \"jsx\": \"react-jsx\",\n    \"baseUrl\": \".\",\n    \"paths\": { \"@/*\": [\"./src/*\"] }\n  },\n  \"include\": [\"src\"]\n}\n",
  "_example/src/mods/hello/seed.ts.tmpl": "import type { Tree } from '@treenity/core/store'\nimport './types'\n\nexport async function seedHello(store: Tree) {\n  if (await store.get('/hello')) return\n  await store.set({\n    $path: '/hello',\n    $type: '{{NAMESPACE}}.hello',\n    message: 'Hello from {{PROJECT_NAME}}!',\n    count: 0,\n  })\n}\n",
  "_example/src/mods/hello/server.ts.tmpl": "import './types'\nimport './service'\n",
  "_example/src/mods/hello/service.ts.tmpl": "import { register } from '@treenity/core/comp'\n\nregister('{{NAMESPACE}}.hello', 'service', async (_node, ctx) => {\n  console.log('hello mod started')\n  return { stop: async () => {} }\n})\n",
  "_example/src/mods/hello/types.ts.tmpl": "import { registerType } from '@treenity/core/comp'\n\nexport class Hello {\n  message = 'Hello, Treenity!'\n  count = 0\n\n  /** @description Increment the visit counter */\n  greet() {\n    this.count++\n    return { message: this.message, count: this.count }\n  }\n}\nregisterType('{{NAMESPACE}}.hello', Hello)\n",
  "_frontend/src/front/App.tsx.tmpl": "export function App() {\n  return (\n    <div className=\"min-h-screen bg-zinc-950 text-zinc-100 flex items-center justify-center\">\n      <div className=\"text-center space-y-4\">\n        <h1 className=\"text-4xl font-bold\">{{PROJECT_NAME}}</h1>\n        <p className=\"text-zinc-400\">Powered by Treenity</p>\n        <div className=\"mt-8 p-4 bg-zinc-900 rounded-lg border border-zinc-800 text-left text-sm font-mono\">\n          <p className=\"text-zinc-500\">// Connect to your treenity server:</p>\n          <p>import {'{'} useNode {'}'} from '@treenity/core/front/hooks'</p>\n          <p className=\"mt-2\">const root = useNode('/')</p>\n        </div>\n      </div>\n    </div>\n  )\n}\n",
  "_frontend/src/front/index.html.tmpl": "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>{{PROJECT_NAME}}</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"./main.tsx\"></script>\n  </body>\n</html>\n",
  "_frontend/src/front/main.tsx.tmpl": "import { createRoot } from 'react-dom/client'\nimport { App } from './App'\nimport './style.css'\n\ncreateRoot(document.getElementById('root')!).render(<App />)\n",
  "_frontend/src/front/style.css.tmpl": "@import 'tailwindcss';\n",
  "_frontend/vite.config.ts.tmpl": "import tailwindcss from '@tailwindcss/vite'\nimport react from '@vitejs/plugin-react'\nimport { defineConfig } from 'vite'\nimport tsconfigPaths from 'vite-tsconfig-paths'\n\nexport default defineConfig({\n  plugins: [tsconfigPaths(), tailwindcss(), react()],\n  root: 'src/front',\n  server: {\n    port: 3210,\n    proxy: {\n      '/trpc/': { target: 'http://127.0.0.1:3211', changeOrigin: true },\n    },\n  },\n})\n"
};
